# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0003_name_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='access_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='name',
            name='archivist_summary',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name='name',
            name='call_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='name',
            name='created_published_by',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='name',
            name='extent',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name='name',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='name',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='name',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
