# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0004_auto_20190412_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='access_conditions',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='name',
            name='created_published_by',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='name',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, null=True, unique=True),
        ),
    ]
