# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0005_auto_20190412_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name',
            old_name='description',
            new_name='summary',
        ),
    ]
