# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0006_auto_20190412_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='created_published_by',
            field=models.CharField(blank=True, max_length=160, verbose_name='Created / Published By'),
        ),
    ]
