# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('name', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
    ]
