# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('call_number', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('summary', tinymce.models.HTMLField(blank=True)),
                ('archivist_summary', tinymce.models.HTMLField(blank=True)),
                ('access_conditions', models.CharField(blank=True, max_length=160)),
                ('created_published_by', models.CharField(blank=True, max_length=160, verbose_name='Created / Published By')),
                ('extent', tinymce.models.HTMLField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=160, null=True, unique=True)),
            ],
        ),
    ]
