# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-11 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0002_auto_20190410_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
            preserve_default=False,
        ),
    ]
