# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0003_auto_20190426_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagulous_Name_keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='tagulous_name_keywords',
            unique_together=set([('slug',)]),
        ),
        migrations.AddField(
            model_name='name',
            name='keywords',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, help_text='Enter a comma-separated tag string', related_name='keyword', to='names.Tagulous_Name_keywords'),
        ),
    ]
