# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import tagulous.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0004_auto_20190426_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.DeleteModel(
            name='Tagulous_Name_keywords',
        ),
        migrations.AlterField(
            model_name='name',
            name='keywords',
            field=models.ManyToManyField(related_name='keyword', to='names.Keyword'),
        ),
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together=set([('slug',)]),
        ),
    ]
