# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0005_auto_20190426_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='keyword', to='names.Keyword'),
        ),
    ]
