# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-21 23:20
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0007_auto_20190428_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='extent',
        ),
        migrations.AddField(
            model_name='name',
            name='bio_hist_note',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Bio./Hist. Note'),
        ),
    ]
