# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-22 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0009_name_archivist_ethics'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='date_published',
            field=models.DateField(auto_now=True),
        ),
    ]
