# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-22 01:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0010_name_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='date_published',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
