# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-22 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0012_name_city_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='city_published',
            field=models.CharField(blank=True, default='Los Angeles', max_length=80, verbose_name='City Published'),
        ),
    ]
