# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0002_recording_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='id',
        ),
        migrations.AddField(
            model_name='recording',
            name='call_number',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recording',
            name='location',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recording',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='recording',
            name='title',
            field=models.CharField(default='', max_length=120, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
