# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 01:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0003_auto_20190412_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='call_number',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='location',
        ),
    ]
