# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 01:22
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0004_auto_20190412_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='transcript',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
