# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0001_initial'),
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='names',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='names.Name'),
            preserve_default=False,
        ),
    ]
