# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-07 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0002_recording_transcript_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='transcript_document',
            field=models.FileField(blank=True, null=True, upload_to='transcripts/'),
        ),
    ]
