# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-07 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0003_auto_20190807_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
