# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-24 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_page_sidebar'),
        ('sidebars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebar',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.Page'),
        ),
    ]
