# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-13 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('title', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('content', tinymce.models.HTMLField(blank=True)),
            ],
        ),
    ]
