# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sidebars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('content', tinymce.models.HTMLField(blank=True)),
                ('sidebar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sidebars.Sidebar')),
            ],
        ),
    ]
