# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-09 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpage',
            name='feed_image',
        ),
    ]
