# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-24 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sidebars', '0003_remove_sidebar_page'),
        ('pages', '0002_remove_page_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='sidebar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sidebars.Sidebar'),
        ),
    ]
