# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-30 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0013_auto_20190822_0106'),
        ('pages', '0003_page_sidebar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronouns', models.CharField(blank=True, max_length=100)),
                ('full_name', models.EmailField(max_length=254)),
                ('first_choice_date', models.DateField()),
                ('first_choice_time', models.CharField(max_length=50)),
                ('second_choice_date', models.DateField()),
                ('second_choice_time', models.CharField(max_length=50)),
                ('items', models.ManyToManyField(to='names.Name')),
            ],
        ),
    ]
