# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-30 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
