# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-30 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20190830_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='first_choice_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='second_choice_time',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
